
services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432"
  php:
    build: .
    restart: always
    ports:
      - "9500:80" # HTTP
      - "9501:443" # HTTPS
      - "9501:443/udp" # HTTP/3
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - database
    extra_hosts:
      - "share-promo-code.zak.dev.localhost=127.0.0.1"
      - "share-promo-code.zak.dev.localhost=::1"
volumes:
  database_data:
  caddy_data:
  caddy_config: